// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuqU1mNLjlvlSCcAdLdSxSzdBXH6gBTLQ',
    appId: '1:241764608287:web:5dadf368a579f63287e82a',
    messagingSenderId: '241764608287',
    projectId: 'ng-express-delivery',
    authDomain: 'ng-express-delivery.firebaseapp.com',
    storageBucket: 'ng-express-delivery.firebasestorage.app',
    measurementId: 'G-BEBM8MXDS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFRatiSwDo3oSMIjdV22MjEZ_fxBAuErI',
    appId: '1:241764608287:android:5facc620048f0cfc87e82a',
    messagingSenderId: '241764608287',
    projectId: 'ng-express-delivery',
    storageBucket: 'ng-express-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDdjxRzHSnhAtHRwV2zQEnSYuIvNUQMhc',
    appId: '1:241764608287:ios:b432dcbedde69a8287e82a',
    messagingSenderId: '241764608287',
    projectId: 'ng-express-delivery',
    storageBucket: 'ng-express-delivery.firebasestorage.app',
    iosBundleId: 'com.example.ngEntregas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDdjxRzHSnhAtHRwV2zQEnSYuIvNUQMhc',
    appId: '1:241764608287:ios:b432dcbedde69a8287e82a',
    messagingSenderId: '241764608287',
    projectId: 'ng-express-delivery',
    storageBucket: 'ng-express-delivery.firebasestorage.app',
    iosBundleId: 'com.example.ngEntregas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuqU1mNLjlvlSCcAdLdSxSzdBXH6gBTLQ',
    appId: '1:241764608287:web:141ebc053a95235087e82a',
    messagingSenderId: '241764608287',
    projectId: 'ng-express-delivery',
    authDomain: 'ng-express-delivery.firebaseapp.com',
    storageBucket: 'ng-express-delivery.firebasestorage.app',
    measurementId: 'G-VWC3LDKCJW',
  );
}
